package com.black.zhan.back.baseInfo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBiUser<M extends BaseBiUser<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setLoginName(java.lang.String loginName) {
		set("LOGIN_NAME", loginName);
		return (M)this;
	}
	
	public java.lang.String getLoginName() {
		return getStr("LOGIN_NAME");
	}

	public M setLoginPwd(java.lang.String loginPwd) {
		set("LOGIN_PWD", loginPwd);
		return (M)this;
	}
	
	public java.lang.String getLoginPwd() {
		return getStr("LOGIN_PWD");
	}

	public M setUserName(java.lang.String userName) {
		set("USER_NAME", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("USER_NAME");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("CREATE_TIME");
	}

	public M setCreateUserId(java.lang.String createUserId) {
		set("CREATE_USER_ID", createUserId);
		return (M)this;
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("CREATE_USER_ID");
	}

	public M setModifyTime(java.lang.String modifyTime) {
		set("MODIFY_TIME", modifyTime);
		return (M)this;
	}
	
	public java.lang.String getModifyTime() {
		return getStr("MODIFY_TIME");
	}

	public M setModifyUserId(java.lang.String modifyUserId) {
		set("MODIFY_USER_ID", modifyUserId);
		return (M)this;
	}
	
	public java.lang.String getModifyUserId() {
		return getStr("MODIFY_USER_ID");
	}

}
