package com.black.zhan.back.baseInfo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBiSysMsg<M extends BaseBiSysMsg<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setFkTableId(java.lang.String fkTableId) {
		set("FK_TABLE_ID", fkTableId);
		return (M)this;
	}
	
	public java.lang.String getFkTableId() {
		return getStr("FK_TABLE_ID");
	}

	public M setNoticeTarget(java.lang.String noticeTarget) {
		set("NOTICE_TARGET", noticeTarget);
		return (M)this;
	}
	
	public java.lang.String getNoticeTarget() {
		return getStr("NOTICE_TARGET");
	}

	public M setNoticeStatus(java.lang.String noticeStatus) {
		set("NOTICE_STATUS", noticeStatus);
		return (M)this;
	}
	
	public java.lang.String getNoticeStatus() {
		return getStr("NOTICE_STATUS");
	}

	public M setNoticeTitle(java.lang.String noticeTitle) {
		set("NOTICE_TITLE", noticeTitle);
		return (M)this;
	}
	
	public java.lang.String getNoticeTitle() {
		return getStr("NOTICE_TITLE");
	}

	public M setNoticeContant(java.lang.String noticeContant) {
		set("NOTICE_CONTANT", noticeContant);
		return (M)this;
	}
	
	public java.lang.String getNoticeContant() {
		return getStr("NOTICE_CONTANT");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("CREATE_TIME");
	}

	public M setCreateUserId(java.lang.String createUserId) {
		set("CREATE_USER_ID", createUserId);
		return (M)this;
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("CREATE_USER_ID");
	}

	public M setModifyTime(java.lang.String modifyTime) {
		set("MODIFY_TIME", modifyTime);
		return (M)this;
	}
	
	public java.lang.String getModifyTime() {
		return getStr("MODIFY_TIME");
	}

	public M setModifyUserId(java.lang.String modifyUserId) {
		set("MODIFY_USER_ID", modifyUserId);
		return (M)this;
	}
	
	public java.lang.String getModifyUserId() {
		return getStr("MODIFY_USER_ID");
	}

}
