package com.black.zhan.back.baseInfo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBiStatusCode<M extends BaseBiStatusCode<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setBizType(java.lang.String bizType) {
		set("BIZ_TYPE", bizType);
		return (M)this;
	}
	
	public java.lang.String getBizType() {
		return getStr("BIZ_TYPE");
	}

	public M setBizName(java.lang.String bizName) {
		set("BIZ_NAME", bizName);
		return (M)this;
	}
	
	public java.lang.String getBizName() {
		return getStr("BIZ_NAME");
	}

	public M setStatusCode(java.lang.String statusCode) {
		set("STATUS_CODE", statusCode);
		return (M)this;
	}
	
	public java.lang.String getStatusCode() {
		return getStr("STATUS_CODE");
	}

	public M setStatusName(java.lang.String statusName) {
		set("STATUS_NAME", statusName);
		return (M)this;
	}
	
	public java.lang.String getStatusName() {
		return getStr("STATUS_NAME");
	}

	public M setStatusOrder(java.lang.Integer statusOrder) {
		set("STATUS_ORDER", statusOrder);
		return (M)this;
	}
	
	public java.lang.Integer getStatusOrder() {
		return getInt("STATUS_ORDER");
	}

	public M setUseStatus(java.lang.String useStatus) {
		set("USE_STATUS", useStatus);
		return (M)this;
	}
	
	public java.lang.String getUseStatus() {
		return getStr("USE_STATUS");
	}

	public M setSelectedStatus(java.lang.String selectedStatus) {
		set("SELECTED_STATUS", selectedStatus);
		return (M)this;
	}
	
	public java.lang.String getSelectedStatus() {
		return getStr("SELECTED_STATUS");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("CREATE_TIME");
	}

	public M setCreateUserId(java.lang.String createUserId) {
		set("CREATE_USER_ID", createUserId);
		return (M)this;
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("CREATE_USER_ID");
	}

	public M setModifyTime(java.lang.String modifyTime) {
		set("MODIFY_TIME", modifyTime);
		return (M)this;
	}
	
	public java.lang.String getModifyTime() {
		return getStr("MODIFY_TIME");
	}

	public M setModifyUserId(java.lang.String modifyUserId) {
		set("MODIFY_USER_ID", modifyUserId);
		return (M)this;
	}
	
	public java.lang.String getModifyUserId() {
		return getStr("MODIFY_USER_ID");
	}

}
