package com.black.zhan.back.baseInfo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBiMenu<M extends BaseBiMenu<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setMenuCode(java.lang.String menuCode) {
		set("MENU_CODE", menuCode);
		return (M)this;
	}
	
	public java.lang.String getMenuCode() {
		return getStr("MENU_CODE");
	}

	public M setMenuName(java.lang.String menuName) {
		set("MENU_NAME", menuName);
		return (M)this;
	}
	
	public java.lang.String getMenuName() {
		return getStr("MENU_NAME");
	}

	public M setMenuPath(java.lang.String menuPath) {
		set("MENU_PATH", menuPath);
		return (M)this;
	}
	
	public java.lang.String getMenuPath() {
		return getStr("MENU_PATH");
	}

	public M setParentMenuCode(java.lang.String parentMenuCode) {
		set("PARENT_MENU_CODE", parentMenuCode);
		return (M)this;
	}
	
	public java.lang.String getParentMenuCode() {
		return getStr("PARENT_MENU_CODE");
	}

	public M setMenuOrder(java.lang.Integer menuOrder) {
		set("MENU_ORDER", menuOrder);
		return (M)this;
	}
	
	public java.lang.Integer getMenuOrder() {
		return getInt("MENU_ORDER");
	}

	public M setSelfPicPath(java.lang.String selfPicPath) {
		set("SELF_PIC_PATH", selfPicPath);
		return (M)this;
	}
	
	public java.lang.String getSelfPicPath() {
		return getStr("SELF_PIC_PATH");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("CREATE_TIME");
	}

	public M setCreateUserId(java.lang.String createUserId) {
		set("CREATE_USER_ID", createUserId);
		return (M)this;
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("CREATE_USER_ID");
	}

	public M setModifyTime(java.lang.String modifyTime) {
		set("MODIFY_TIME", modifyTime);
		return (M)this;
	}
	
	public java.lang.String getModifyTime() {
		return getStr("MODIFY_TIME");
	}

	public M setModifyUserId(java.lang.String modifyUserId) {
		set("MODIFY_USER_ID", modifyUserId);
		return (M)this;
	}
	
	public java.lang.String getModifyUserId() {
		return getStr("MODIFY_USER_ID");
	}

}
