package com.black.zhan.back.baseInfo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBiRole<M extends BaseBiRole<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setRoleCode(java.lang.String roleCode) {
		set("ROLE_CODE", roleCode);
		return (M)this;
	}
	
	public java.lang.String getRoleCode() {
		return getStr("ROLE_CODE");
	}

	public M setRoleName(java.lang.String roleName) {
		set("ROLE_NAME", roleName);
		return (M)this;
	}
	
	public java.lang.String getRoleName() {
		return getStr("ROLE_NAME");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("CREATE_TIME", createTime);
		return (M)this;
	}
	
	public java.lang.String getCreateTime() {
		return getStr("CREATE_TIME");
	}

	public M setCreateUserId(java.lang.String createUserId) {
		set("CREATE_USER_ID", createUserId);
		return (M)this;
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("CREATE_USER_ID");
	}

	public M setModifyTime(java.lang.String modifyTime) {
		set("MODIFY_TIME", modifyTime);
		return (M)this;
	}
	
	public java.lang.String getModifyTime() {
		return getStr("MODIFY_TIME");
	}

	public M setModifyUserId(java.lang.String modifyUserId) {
		set("MODIFY_USER_ID", modifyUserId);
		return (M)this;
	}
	
	public java.lang.String getModifyUserId() {
		return getStr("MODIFY_USER_ID");
	}

}
