package com.black.zhan.back.baseInfo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBiRoleMenu<M extends BaseBiRoleMenu<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}
	
	public java.lang.String getID() {
		return getStr("ID");
	}

	public M setFkBiRole(java.lang.String fkBiRole) {
		set("FK_BI_ROLE", fkBiRole);
		return (M)this;
	}
	
	public java.lang.String getFkBiRole() {
		return getStr("FK_BI_ROLE");
	}

	public M setFkBiMenu(java.lang.String fkBiMenu) {
		set("FK_BI_MENU", fkBiMenu);
		return (M)this;
	}
	
	public java.lang.String getFkBiMenu() {
		return getStr("FK_BI_MENU");
	}

}
