package com.black.zhan.jfinal.common;

import com.black.zhan.back.baseInfo.model._BaseInfoMappingKit;
import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		_BaseInfoMappingKit.mapping(arp);
		// 有再生成的，则继续往下加
	}
}

