package com.black.zhan.back.baseInfo.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _BaseInfoMappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _BaseInfoMappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("bi_dict", "ID", BiDict.class);
		arp.addMapping("bi_menu", "ID", BiMenu.class);
		arp.addMapping("bi_role", "ID", BiRole.class);
		arp.addMapping("bi_role_menu", "ID", BiRoleMenu.class);
		arp.addMapping("bi_status_code", "ID", BiStatusCode.class);
		arp.addMapping("bi_sys_msg", "ID", BiSysMsg.class);
		arp.addMapping("bi_user", "ID", BiUser.class);
		arp.addMapping("bi_user_role", "ID", BiUserRole.class);
	}
}

