package com.black.zhan.back.baseInfo.model;

import com.black.zhan.back.baseInfo.model.base.BaseBiMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BiMenu extends BaseBiMenu<BiMenu> {
	public static final BiMenu dao = new BiMenu().dao();
}
