package com.black.zhan.back.baseInfo.model;

import com.black.zhan.back.baseInfo.model.base.BaseBiRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BiRoleMenu extends BaseBiRoleMenu<BiRoleMenu> {
	public static final BiRoleMenu dao = new BiRoleMenu().dao();
}
