package com.black.zhan.back.baseInfo.model;

import com.black.zhan.back.baseInfo.model.base.BaseBiStatusCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BiStatusCode extends BaseBiStatusCode<BiStatusCode> {
	public static final BiStatusCode dao = new BiStatusCode().dao();
}
