package com.black.zhan.back.baseInfo.model;

import com.black.zhan.back.baseInfo.model.base.BaseBiSysMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BiSysMsg extends BaseBiSysMsg<BiSysMsg> {
	public static final BiSysMsg dao = new BiSysMsg().dao();
}
