package com.black.zhan.back.baseInfo.model;

import com.black.zhan.back.baseInfo.model.base.BaseBiUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BiUser extends BaseBiUser<BiUser> {
	public static final BiUser dao = new BiUser().dao();
}
